### ISSUE TITLE
Unable to install the plugin in Bamboo 5.10.0

### ISSUE THREAD

**Issue by aurobindodash** [onepremise/gReview#36]
Hi Team,  

We have tried installing the plugin in Bamboo 5.10.0. However, we are getting the below error:  

This add-on could not be loaded. It has one or more errors that prevent it from being enabled. Refer to the logs for more information.  

We could not find any specific error in the logs.  We have tried both 1.4.6.7, 1.4.6.5 versions.

**Comment by onepremise** [comment]
Hello, sorry to hear your having trouble. Please try uninstalling and reinstalling again in the plugin manager. Scan the log and see if you can catch an Exception. There maybe an issue with felix and your maven repository, if you are getting dependency errors. Sometimes you have to flush out your maven repository and let it repopulate. I'll try installing on Bamboo 5.10.0 to see if I can reproduce your error. Let me know how it goes. Thanks!

**Comment by aurobindodash** [comment]
Hi,

We have tried to install multiple times with out luck. The plugin is in disabled state. Kindly refer to the attached screenshot.

Regards,
Auro.
![greview error-bamboo](https://cloud.githubusercontent.com/assets/20300145/16645048/ac90e860-443e-11e6-919a-d30dc2908911.png)

**Comment by onepremise** [comment]
Great! Glad to hear. Thanks for letting me know.
